# Questão 6

## Importando Bibliotecas

In [ ]:
import pandas as pd
from matplotlib import pyplot as plt

pd.set_option('display.max_columns', None)

## Carregando Dados

In [2]:
vendas = pd.read_csv('../../datasets/vendas.csv')

In [5]:
vendas['sale_date'] = pd.to_datetime(vendas['sale_date'])

vendas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9895 entries, 0 to 9894
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          9895 non-null   int64
 1   client_id   9895 non-null   int64
 2   product_id  9895 non-null   int64
 3   qtd         9895 non-null   int64
 4   total       9895 non-null   float64
 5   sale_date   9895 non-null   datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(4)
memory usage: 464.0 KB

## Criando Calendário

In [6]:
datas = pd.date_range(start='2023-01-01', end='2024-12-31', freq='D')

calendario = pd.DataFrame({'data': datas})

mapa_dias = {
    'Monday': 'Segunda-feira',
    'Tuesday': 'Terça-feira',
    'Wednesday': 'Quarta-feira',
    'Thursday': 'Quinta-feira',
    'Friday': 'Sexta-feira',
    'Saturday': 'Sábado',
    'Sunday': 'Domingo'
}

calendario['dia_da_semana'] = calendario['data'].dt.day_name().map(mapa_dias)

calendario.head()

        data  dia_da_semana
0 2023-01-01        Domingo
1 2023-01-02  Segunda-feira
2 2023-01-03    Terça-feira
3 2023-01-04   Quarta-feira
4 2023-01-05   Quinta-feira

## Fazendo Cálculos

In [11]:
vendas_em_cada_dia = calendario.merge(
    vendas,
    left_on='data',
    right_on='sale_date',
    how='left'
)


vendas_por_dia = (
    vendas_em_cada_dia.
        groupby(['data', 'dia_da_semana'], as_index=False)
    ['total'].
        sum().
        sort_values('data')
)

vendas_por_dia.head()

        data  dia_da_semana       total
0 2023-01-01        Domingo  4207939.25
1 2023-01-02  Segunda-feira  5102799.80
2 2023-01-03    Terça-feira  8299127.05
3 2023-01-04   Quarta-feira  4707759.40
4 2023-01-05   Quinta-feira  5525706.90

In [17]:
vendas_por_dia_da_semana_media = (
    vendas_por_dia.
        groupby('dia_da_semana')
    ['total'].
        mean().
        sort_values()
)

print(f"Dia da Semana com menor média de vendas: {vendas_por_dia_da_semana_media.index[0]}")

print(f"Média de vendas: {vendas_por_dia_da_semana_media.iloc[0]:,.2f}")

Dia da Semana com menor média de vendas: Domingo
Média de vendas: 3,319,503.57