# Questão 2

## Importando Bibliotecas

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

## Carregando Dados

In [2]:
produtos = pd.read_csv('../../datasets/produtos_raw.csv')

produtos.sample(10)

,name,price,code,actual_category
81,Motor Elétrico Honda Mako Axis 131HP,R$ 121761.56,78,propulsão
87,Motor de Popa Torqeedo Zenith Peak Thrust 212HP,R$ 43423.88,84,propulsão
103,Motor Elétrico Honda Vector Abyss 220HP,R$ 104600.24,100,PrOpUlSãO
89,Motor Diesel Volvo Helix Evo Force 144HP,R$ 93523.13,86,Propulsam
44,GPS Simrad Zen Hydra Peak,R$ 10806.84,44,EletrônicoS
114,Boia de Arqueamento Danforth Aero Dash,R$ 4285.23,111,A N C O R A G E M
56,Motor Elétrico Torqeedo Velocity Swift 74HP,R$ 42988.77,56,propulsao
22,Piloto Automático Furuno Torque Peak,R$ 11178.63,23,Eletroniscos
37,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,ELEtRÔNICOS
93,Motor de Popa Yamaha Thrust Marlin Nexus 182HP,R$ 79097.33,90,PROPULSAO

In [3]:
produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    object
 1   price            157 non-null    object
 2   code             157 non-null    int64
 3   actual_category  157 non-null    object
dtypes: int64(1), object(3)
memory usage: 5.0+ KB

## Renomeando Colunas

As colunas `code` e `actual_category` serão renomeadas para garantir consistência e simplicidade.

In [4]:
produtos.rename(
    columns={
        'code': 'id',
        'actual_category': 'category'
    },
    inplace=True
)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      157 non-null    object
 1   price     157 non-null    object
 2   id        157 non-null    int64
 3   category  157 non-null    object
dtypes: int64(1), object(3)
memory usage: 5.0+ KB

## Analisando Duplicatas

In [5]:
print(produtos.duplicated().sum())

0

In [6]:
print(produtos.duplicated(subset='id').sum())

7

In [7]:
print(produtos.duplicated(subset='name').sum())

7

In [8]:
print(produtos.duplicated(subset='price').sum())

7

In [9]:
produtos[produtos.duplicated(subset='price', keep=False)]

,name,price,id,category
36,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,E L E T R Ô N I C O S
37,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,ELEtRÔNICOS
62,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,P R O P U L S Ã O
63,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Propução
64,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,propulsão
65,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Prop
124,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,AncorageM
131,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,Encoragem
132,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,Encoragi
150,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,AncorajeM
151,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,Ancoragen

Temos 7 produtos duplicados, com as colunas `name`, `price` e `id` iguais. Vamos removê-los.

In [10]:
produtos.drop_duplicates(
    subset='id',
    inplace=True
)

produtos.reset_index(
    drop=True,
    inplace=True
)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      150 non-null    object
 1   price     150 non-null    object
 2   id        150 non-null    int64
 3   category  150 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.8+ KB

## Padronizando Colunas

A coluna `price` não está com tipo numério e a coluna `category` possui formato fora de padrão. Vamos padronizar para poder normalizar os dados.

In [11]:
def fix_category(row):
    product_id = row['id']
    if product_id <= 50:
        return 'eletrônicos'
    elif product_id  <= 100:
        return 'propulsão'
    else:
        return 'ancoragem'

In [12]:
produtos['price'] = produtos['price'].apply(lambda x: x[3:]).astype('float')

produtos['category'] = produtos.apply(fix_category, axis=1)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      150 non-null    object
 1   price     150 non-null    float64
 2   id        150 non-null    int64
 3   category  150 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 4.8+ KB

In [13]:
produtos.sample(10)

,name,price,id,category
19,Radar AIS Marlin,30833.44,20,eletrônicos
0,Transponder AIS Maré Magnum,33122.52,1,eletrônicos
133,Âncora Bruce Core Pulse,1892.72,133,ancoragem
75,Motor Diesel Honda Aero 205HP,148198.23,76,propulsão
63,Motor Elétrico Yamaha Swift Drift Current 265HP,111505.55,64,propulsão
38,GPS Furuno Vector,29632.83,39,eletrônicos
143,Âncora Delta Hydra Kraken Velocity,4436.43,143,ancoragem
149,Cabo de Nylon Danforth Magnum Vox,1645.66,150,ancoragem
55,Motor Elétrico Torqeedo Velocity Swift 74HP,42988.77,56,propulsão
147,Âncora Delta Force Barracuda Mako,4785.56,148,ancoragem

## Normalização

Vamos criar uma `DataFrame` com as categorias e deixar apenas uma id numérica com os produtos.

In [14]:
categorias = pd.DataFrame(
    {
    'id': [1, 2, 3],
    'name': ['eletrônicos', 'propulsão', 'ancoragem']
    }
)

produtos = (
    produtos.
        merge(
            categorias,
            left_on='category',
            right_on='name'
        ).drop(
            columns=['name_y', 'category']
        ).rename(
            columns={
                'name_x': 'name',
                'id_x': 'id',
                'id_y': 'category_id'
            }
        )
)

In [15]:
produtos.sample(5)

                                            name      price   id  category_id
108         Cabo de Nylon Danforth Evo Aqua Mako     622.70  109            3
136               Cabo de Nylon Bruce Flux Hydro    1973.50  136            3
138  Boia de Arqueamento Delta Peak Boost Thrust    4183.05  138            3
115   Cabo de Nylon Delta Velocity Oceanic Abyss    2575.52  116            3
61             Motor Diesel Yanmar Velocity 37HP  102221.97   62            2

In [16]:
categorias.head()

   id         name
0   1  eletrônicos
1   2    propulsão
2   3    ancoragem

In [19]:
produtos.to_csv('../../datasets/produtos.csv', index=False, encoding='utf-8')

categorias.to_csv('../../datasets/categorias.csv', index=False, encoding='utf-8')