# Questão 2

## Importando Bibliotecas

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

## Carregando Dados

In [2]:
produtos = pd.read_csv('../../datasets/produtos_raw.csv')

produtos.sample(10)

,name,price,code,actual_category
98,Motor Diesel Honda Leviathan 133HP,R$ 69808.04,95,P R O P U L S Ã O
3,Rádio AIS Hydro Tidal Zen,R$ 3381.88,4,Eletrunicos
40,Sonda Furuno Maré Tidal,R$ 14184.04,40,eLeTrÔnIcOs
24,Rádio Lowrance Nitro Thrust Barracuda,R$ 12126.46,25,Eletrunicos
88,Motor de Popa Parsun Impulse 162HP,R$ 38578.7,85,P R O P U L S Ã O
32,Transponder Garmin Drift Vortex Marlin,R$ 6715.77,33,ELETRONICOS
85,Motor Elétrico Volvo Nautic Vox 118HP,R$ 51634.04,82,P R O P U L S Ã O
100,Motor de Popa Tohatsu Evo 168HP,R$ 135335.07,97,P R O P U L S Ã O
114,Boia de Arqueamento Danforth Aero Dash,R$ 4285.23,111,A N C O R A G E M
156,Cabo de Nylon Danforth Magnum Vox,R$ 1645.66,150,Ancorajem

In [3]:
produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    object
 1   price            157 non-null    object
 2   code             157 non-null    int64
 3   actual_category  157 non-null    object
dtypes: int64(1), object(3)
memory usage: 5.0+ KB

## Renomeando Colunas

As colunas `code` e `actual_category` serão renomeadas para garantir consistência e simplicidade.

In [4]:
produtos.rename(
    columns={
        'code': 'id',
        'actual_category': 'category'
    },
    inplace=True
)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      157 non-null    object
 1   price     157 non-null    object
 2   id        157 non-null    int64
 3   category  157 non-null    object
dtypes: int64(1), object(3)
memory usage: 5.0+ KB

## Analisando Duplicatas

In [5]:
print(produtos.duplicated().sum())

0

In [6]:
print(produtos.duplicated(subset='id').sum())

7

In [7]:
print(produtos.duplicated(subset='name').sum())

7

In [8]:
print(produtos.duplicated(subset='price').sum())

7

In [9]:
produtos[produtos.duplicated(subset='price', keep=False)]

,name,price,id,category
36,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,E L E T R Ô N I C O S
37,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,ELEtRÔNICOS
62,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,P R O P U L S Ã O
63,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Propução
64,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,propulsão
65,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Prop
124,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,AncorageM
131,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,Encoragem
132,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,Encoragi
150,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,AncorajeM
151,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,Ancoragen

Temos 7 produtos duplicados, com as colunas `name`, `price` e `id` iguais. Vamos removê-los.

In [10]:
produtos.drop_duplicates(
    subset='id',
    inplace=True
)

produtos.reset_index(
    drop=True,
    inplace=True
)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      150 non-null    object
 1   price     150 non-null    object
 2   id        150 non-null    int64
 3   category  150 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.8+ KB

## Padronizando Colunas

A coluna `price` não está com tipo numério e a coluna `category` possui formato fora de padrão. Vamos padronizar para poder normalizar os dados.

In [11]:
def fix_category(row):
    product_id = row['id']
    if product_id <= 50:
        return 'eletrônicos'
    elif product_id  <= 100:
        return 'propulsão'
    else:
        return 'ancoragem'

In [12]:
produtos['price'] = produtos['price'].apply(lambda x: x[3:]).astype('float')

produtos['category'] = produtos.apply(fix_category, axis=1)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      150 non-null    object
 1   price     150 non-null    float64
 2   id        150 non-null    int64
 3   category  150 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 4.8+ KB

In [13]:
produtos.sample(10)

                                             name      price  id     category
87    Motor Diesel Tohatsu Kinetic Poseidon 113HP   48336.49  88    propulsão
52  Motor Elétrico Torqeedo Zen Titan Hydra 129HP   53675.01  53    propulsão
36                   GPS Lowrance Evo Storm Drift    6067.71  37  eletrônicos
37                                Rádio AIS Force   26461.14  38  eletrônicos
61              Motor Diesel Yanmar Velocity 37HP  102221.97  62    propulsão
56       Motor de Popa Honda Vector Kinetic 174HP  118790.57  57    propulsão
0                     Transponder AIS Maré Magnum   33122.52   1  eletrônicos
10            GPS Furuno Swift Leviathan Poseidon   36231.91  11  eletrônicos
97  Motor Diesel Parsun Velocity Abyss Orca 235HP   79361.13  98    propulsão
38                              GPS Furuno Vector   29632.83  39  eletrônicos

## Normalização

Vamos criar uma `DataFrame` com as categorias e deixar apenas uma id numérica com os produtos.

In [14]:
categories = pd.DataFrame(
    {
    'id': [1, 2, 3],
    'name': ['eletrônicos', 'propulsão', 'ancoragem']
    }
)

produtos = (
    produtos.
        merge(
            categories,
            left_on='category',
            right_on='name'
        ).drop(
            columns=['name_y', 'category']
        ).rename(
            columns={
                'name_x': 'name',
                'id_x': 'id',
                'id_y': 'category_id'
            }
        )
)

In [15]:
produtos.sample(5)

                                     name      price  id  category_id
98  Motor Elétrico Honda Flux Ultra 273HP  107266.66  99            2
6                           Radar AIS Zen   19518.77   7            1
16                Rádio AIS Oceanic Pulse   14038.78  17            1
44                     GPS Furuno Current    9903.71  45            1
33           Transponder AIS Helix Torque    4917.53  34            1

In [16]:
categories.head()

   id         name
0   1  eletrônicos
1   2    propulsão
2   3    ancoragem