# Questão 3

## Importando Bibliotecas

In [1]:
import pandas as pd
import json

## Carregando Arquivos

Vamos utilizar a biblioteca `json` para transformar o arquivo em um dicionário.

In [2]:
with open("../../datasets/custos_importacao.json", 'r', encoding='utf-8') as f:
    dados = json.load(f)

## Transformando em DataFrame

Para transformar o dicionário aninhado em uma `Dataframe`, vamos utilizar a função nativa do Pandas `pd.json_normalize`.

In [3]:
df = pd.json_normalize(
    dados, 
    record_path=['historic_data'], 
    meta=['product_id', 'product_name', 'category']
)

ordem_colunas = ['product_id', 'product_name', 'category', 'start_date', 'usd_price']
custos_importacao = df[ordem_colunas]

In [4]:
custos_importacao.sample(10)

,product_id,product_name,category,start_date,usd_price
795,95,Motor Diesel Honda Leviathan 133HP,propulsão,02/09/2016,21529.08
620,73,Motor de Popa Torqeedo Core Hydra Flux 162HP,propulsão,22/03/2024,28694.54
614,73,Motor de Popa Torqeedo Core Hydra Flux 162HP,propulsão,29/10/2018,39370.75
179,21,GPS AIS Nautic Thrust,eletrônicos,04/09/2017,2783.21
63,9,Transponder AIS Titan Pulse,eletrônicos,10/12/2020,7808.97
91,12,GPS AIS Drift Flux Vox,eletrônicos,21/03/2016,752.61
1020,123,Cabo de Nylon Danforth Orca Aero,ancoragem,02/09/2022,535.37
536,63,Motor Elétrico Torqeedo Ion Orca Vox 186HP,propulsão,15/05/2025,24849.56
645,76,Motor Diesel Honda Aero 205HP,propulsão,23/08/2024,26819.81
1252,150,Cabo de Nylon Danforth Magnum Vox,ancoragem,19/02/2019,442.38

In [5]:
custos_importacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1260 non-null   object
 1   product_name  1260 non-null   object
 2   category      1260 non-null   object
 3   start_date    1260 non-null   object
 4   usd_price     1260 non-null   float64
dtypes: float64(1), object(4)
memory usage: 49.3+ KB

## Corrigindo Tipos de Dados

As colunas `product_id` e `start_date` possuem tipos errados. Vamos corrigir os tipos.

In [6]:
custos_importacao['product_id'] = custos_importacao['product_id'].astype('int')

custos_importacao['start_date'] =  pd.to_datetime(custos_importacao['start_date'], format='%d/%m/%Y')

In [7]:
custos_importacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1260 entries, 0 to 1259
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    1260 non-null   int64
 1   product_name  1260 non-null   object
 2   category      1260 non-null   object
 3   start_date    1260 non-null   datetime64[ns]
 4   usd_price     1260 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(2)
memory usage: 49.3+ KB

## Normalizando

In [9]:
custos_importacao = (
    custos_importacao.
        drop(
            columns=['category', 'product_name']
        )
)

In [10]:
custos_importacao.sample(5)

      product_id start_date  usd_price
1202         144 2024-09-17     402.54
1223         147 2022-03-21     610.17
51             7 2022-12-12    3678.62
429           50 2016-08-03    3445.47
710           85 2023-11-23    7885.27

## Carregando o .CSV

In [11]:
custos_importacao.to_csv('../../datasets/custos_importacao.csv', index=False, encoding='utf-8')