# Questão 2

## Importando Bibliotecas

In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

## Carregando Dados

In [2]:
produtos = pd.read_csv('../../datasets/produtos_raw.csv')

produtos.sample(10)

,name,price,code,actual_category
15,Sonda Garmin Axis,R$ 30005.99,16,eletrônicos
54,Motor de Popa Yamaha Evo Dash 155HP,R$ 121534.82,54,Propulssão
105,Cabo de Nylon Bruce Nexus,R$ 832.02,102,AnCoRaGeM
128,Corrente Delta Axis,R$ 3769.93,124,AncorageM
68,Motor de Popa Torqeedo Nautic Swift 223HP,R$ 25557.7,65,Propulção
84,Motor Elétrico Torqeedo Barracuda Magnum Helix...,R$ 122148.49,81,Propulçao
95,Motor Elétrico Yamaha Nautic Kraken 133HP,R$ 88854.1,92,Propução
118,Cabo de Nylon Delta Force Magnum Leviathan,R$ 830.59,115,Ancoraguem
31,Sonda AIS Impulse Oceanic Zenith,R$ 12502.46,32,ELETRONICOS
85,Motor Elétrico Volvo Nautic Vox 118HP,R$ 51634.04,82,P R O P U L S Ã O

In [3]:
produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             157 non-null    object
 1   price            157 non-null    object
 2   code             157 non-null    int64
 3   actual_category  157 non-null    object
dtypes: int64(1), object(3)
memory usage: 5.0+ KB

## Renomeando Colunas

As colunas `code` e `actual_category` serão renomeadas para garantir consistência e simplicidade.

In [4]:
produtos.rename(
    columns={
        'code': 'id',
        'actual_category': 'category'
    },
    inplace=True
)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      157 non-null    object
 1   price     157 non-null    object
 2   id        157 non-null    int64
 3   category  157 non-null    object
dtypes: int64(1), object(3)
memory usage: 5.0+ KB

## Analisando Duplicatas

In [5]:
print(produtos.duplicated().sum())

0

In [6]:
print(produtos.duplicated(subset='id').sum())

7

In [7]:
print(produtos.duplicated(subset='name').sum())

7

In [8]:
print(produtos.duplicated(subset='price').sum())

7

In [9]:
produtos[produtos.duplicated(subset='price', keep=False)]

,name,price,id,category
36,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,E L E T R Ô N I C O S
37,GPS Lowrance Evo Storm Drift,R$ 6067.71,37,ELEtRÔNICOS
62,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,P R O P U L S Ã O
63,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Propução
64,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,propulsão
65,Motor Diesel Yanmar Velocity 37HP,R$ 102221.97,62,Prop
124,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,AncorageM
131,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,Encoragem
132,Cabo de Nylon Delta Velocity Core Mako,R$ 1549.35,127,Encoragi
150,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,AncorajeM
151,Boia de Arqueamento Delta Nexus,R$ 4349.86,145,Ancoragen

Temos 7 produtos duplicados, com as colunas `name`, `price` e `id` iguais. Vamos removê-los.

In [10]:
produtos.drop_duplicates(
    subset='id',
    inplace=True
)

produtos.reset_index(
    drop=True,
    inplace=True
)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      150 non-null    object
 1   price     150 non-null    object
 2   id        150 non-null    int64
 3   category  150 non-null    object
dtypes: int64(1), object(3)
memory usage: 4.8+ KB

## Padronizando Colunas

A coluna `price` não está com tipo numério e a coluna `category` possui formato fora de padrão. Vamos padronizar para poder normalizar os dados.

In [11]:
def fix_category(string: str) -> str:
    s = string.lower()
    if s.startswith('e'):
        return 'eletrônicos'
    if s.startswith('p'):
        return 'propulsão'
    if s.startswith('a'):
        return 'ancoragem'
    return ''

In [12]:
produtos['price'] = produtos['price'].apply(lambda x: x[3:]).astype('float')

produtos['category'] = produtos['category'].apply(fix_category)

produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      150 non-null    object
 1   price     150 non-null    float64
 2   id        150 non-null    int64
 3   category  150 non-null    object
dtypes: float64(1), int64(1), object(2)
memory usage: 4.8+ KB

## Normalização

Vamos criar uma `DataFrame` com as categorias e deixar apenas uma id numérica com os produtos.

In [13]:
categories = pd.DataFrame(
    {
    'id': [1, 2, 3],
    'name': ['eletrônicos', 'propulsão', 'ancoragem']
    }
)

produtos = (
    produtos.
        merge(
            categories,
            left_on='category',
            right_on='name'
        ).drop(
            columns=['name_y', 'category']
        ).rename(
            columns={
                'name_x': 'name',
                'id_x': 'id',
                'id_y': 'category_id'
            }
        )
)

In [14]:
produtos.sample(5)

                                             name      price   id  category_id
113  Boia de Arqueamento Danforth Tidal Zen Swift     799.29  114            3
43                      GPS Simrad Zen Hydra Peak   10806.84   44            1
25       Piloto Automático Furuno Core Boost Flux   17283.18   26            1
81          Motor Elétrico Volvo Nautic Vox 118HP   51634.04   82            2
56       Motor de Popa Honda Vector Kinetic 174HP  118790.57   57            2

In [15]:
categories.head()

   id         name
0   1  eletrônicos
1   2    propulsão
2   3    ancoragem