In [1]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [2]:
vendas = pd.read_csv('../../datasets/vendas.csv')

produtos = pd.read_csv('../../datasets/produtos.csv')

categorias = pd.read_csv('../../datasets/categorias.csv')

In [3]:
vendas_com_categoria = vendas.merge(
    produtos[
        ['id', 'category_id']
        ],
    left_on='product_id',
    right_on='category_id'
)

dados_clientes = (
    vendas_com_categoria.
        groupby('client_id').
        agg({
            'total': 'mean',
            'category_id': 'nunique'
        })
)

dados_clientes.rename(
    columns={
        'total': 'ticket_medio',
        'category_id': 'diversidade'
    },
    inplace=True
)

dados_clientes

            ticket_medio  diversidade
client_id
1          178230.430000            2
2          100429.100000            2
3          126201.140000            3
4          242028.187500            2
5          194210.075000            2
6          210616.110000            2
7          193734.314286            3
8           98363.050000            3
9          196994.060000            2
10         151179.875000            1
11          87774.950000            1
12         169948.983333            3
13          84950.133333            2
14         173626.412500            3
15          91491.362500            3
16         244055.770000            2
17         133677.425000            2
18         325152.700000            1
19          92296.933333            3
20         282124.820000            2
21          93606.050000            3
22         155627.850000            3
23         110377.775000            2
24          68422.112500            2
25          79807.964286            3
26         131135.000000            2
27          62008.062500            3
28          17145.600000            1
29         226901.525000            2
30         170447.000000            3
31         163206.370000            2
32          80957.262500            2
33          36097.000000            1
34         126339.000000            1
35         430593.000000            1
36         104609.310000            3
37         180967.170000            2
38          90048.700000            3
39         130641.037500            3
40          75364.575000            3
41         114763.175000            2
42         190543.975000            3
43         117697.860000            2
44         184250.083333            2
45         224895.250000            2
46         223260.600000            2
47         163248.141667            3
48         130832.500000            3
49         247020.000000            3

In [4]:
clientes_fieis = (
    dados_clientes
        [dados_clientes['diversidade'] >= 3].
        sort_values('ticket_medio', ascending= False).
        head(10)
)

clientes_fieis

            ticket_medio  diversidade
client_id
49         247020.000000            3
7          193734.314286            3
42         190543.975000            3
14         173626.412500            3
30         170447.000000            3
12         169948.983333            3
47         163248.141667            3
22         155627.850000            3
48         130832.500000            3
39         130641.037500            3

In [5]:
ranking_categorias = (
    vendas_com_categoria
    [vendas_com_categoria['client_id'].isin(clientes_fieis.index)].
        groupby('category_id')
    ['qtd'].
        sum().
        sort_values(ascending=False)
)

ranking_categorias

category_id
2    10050
1     6800
3     6250
Name: qtd, dtype: int64